version: '3.8'

services:
  backend:
    build:
      context: ./apps/backend-api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    restart: always

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
